# Generated by Django 5.0.4 on 2024-07-15 18:23

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "name_slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=32,
                        populate_from=("name",),
                        unique=True,
                    ),
                ),
                ("rpc_url", models.URLField()),
                ("explorer_url", models.URLField()),
                ("evm_compat", models.BooleanField()),
                (
                    "evm_chain_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="chain",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("evm_chain_id__isnull", False), ("evm_compat", True)),
                    models.Q(("evm_chain_id__isnull", True), ("evm_compat", False)),
                    _connector="OR",
                ),
                name="evm_chain_id_check",
            ),
        ),
    ]
