# Generated by Django 5.0.4 on 2024-07-15 18:24

from django.db import migrations


def create_near_chain(apps, schema_editor):
    Chain = apps.get_model("chains", "Chain")
    # Create the "near" chain
    near_chain, created = Chain.objects.get_or_create(
        name="NEAR", defaults={"evm_compat": False}
    )

    # Set "near" chain as the default for all existing accounts
    Account = apps.get_model("accounts", "Account")
    Account.objects.update(chain=near_chain)
    print("Updated all accounts to use NEAR chain")


class Migration(migrations.Migration):

    dependencies = [("chains", "0001_initial"), ("accounts", "0004_account_chain")]

    operations = [
        migrations.RunPython(create_near_chain),
    ]
