# Generated by Django 5.0.4 on 2024-05-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activity_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("action_result", "type")},
        ),
    ]
