# Generated by Django 5.0.4 on 2024-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_activity_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="tx_hash",
            field=models.CharField(
                help_text="Transaction hash.",
                max_length=64,
                null=True,
                verbose_name="transaction hash",
            ),
        ),
    ]
