# Generated by Django 5.0.4 on 2026-03-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="verification id",
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        help_text="Employer Identification Number (XX-XXXXXXX).",
                        max_length=10,
                        verbose_name="EIN",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Organization legal name from IRS records.",
                        max_length=255,
                        verbose_name="legal name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="city",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="US state code (e.g. CA, NY).",
                        max_length=2,
                        null=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="zip code",
                    ),
                ),
                (
                    "subsection_code",
                    models.IntegerField(
                        blank=True,
                        help_text="IRS subsection code. 3 = 501(c)(3).",
                        null=True,
                        verbose_name="subsection code",
                    ),
                ),
                (
                    "ntee_code",
                    models.CharField(
                        blank=True,
                        help_text="National Taxonomy of Exempt Entities code.",
                        max_length=10,
                        null=True,
                        verbose_name="NTEE code",
                    ),
                ),
                (
                    "ruling_date",
                    models.CharField(
                        blank=True,
                        help_text="Date IRS granted tax-exempt status.",
                        max_length=20,
                        null=True,
                        verbose_name="ruling date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=32,
                        verbose_name="verification status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for rejection if verification failed.",
                        max_length=255,
                        null=True,
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="submitted at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        help_text="NEAR account for this organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_verification",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Verification",
                "verbose_name_plural": "Organization Verifications",
            },
        ),
    ]
