# Generated by Django 5.0.4 on 2024-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="On-chain account address.",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="address",
                    ),
                ),
                (
                    "total_donations_in_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total donations received in USD.",
                        max_digits=20,
                        verbose_name="total donations received in USD",
                    ),
                ),
                (
                    "total_donations_out_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total donated in USD.",
                        max_digits=20,
                        verbose_name="total donations sent in USD",
                    ),
                ),
                (
                    "total_matching_pool_allocations_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total matching pool allocations in USD.",
                        max_digits=20,
                        verbose_name="total matching pool allocations in USD",
                    ),
                ),
                (
                    "donors_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of donors.",
                        verbose_name="donors count",
                    ),
                ),
            ],
        ),
    ]
