# Generated by Django 5.0.4 on 2024-07-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_options"),
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                help_text="Blockchain this account is located on.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                related_query_name="account",
                to="chains.chain",
            ),
        ),
    ]
