# Generated by Django 5.0.4 on 2024-07-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_chain"),
        ("chains", "0002_add_near_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="chain",
            field=models.ForeignKey(
                help_text="Blockchain this account is located on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                related_query_name="account",
                to="chains.chain",
            ),
        ),
    ]
