# Generated by Django 5.0.6 on 2024-07-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="near_social_profile_data",
            field=models.JSONField(
                blank=True,
                help_text="NEAR social data contained under 'profile' key.",
                null=True,
                verbose_name="NEAR social profile data",
            ),
        ),
    ]
