# Generated by Django 5.0.4 on 2024-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("donations", "0001_initial"),
        ("pots", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donation",
            name="unique_pot_on_chain_id",
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                fields=("on_chain_id", "pot"), name="unique_pot_on_chain_id"
            ),
        ),
    ]
