# Generated by Django 5.0.4 on 2024-04-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("donations", "0001_initial"),
        ("pots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="on_chain_id",
            field=models.IntegerField(
                blank=True,
                help_text="Donation id in contract",
                null=True,
                verbose_name="contract donation id",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="total_amount_usd",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Total amount in USD.",
                max_digits=20,
                null=True,
                verbose_name="total amount in USD",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                fields=("on_chain_id", "pot"), name="unique_pot_on_chain_id"
            ),
        ),
    ]
