# Generated by Django 5.0.4 on 2024-04-19 18:08

from django.db import migrations
from django.db.models import F

from ..models import Donation


def populate_on_chain_id(apps, schema_editor):
    Donation.objects.all().update(on_chain_id=F("id"))


class Migration(migrations.Migration):

    dependencies = [
        (
            "donations",
            "0002_donation_on_chain_id_alter_donation_total_amount_usd_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_on_chain_id),
    ]
