# Generated by Django 5.0.4 on 2024-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_populate_on_chain_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="on_chain_id",
            field=models.IntegerField(
                help_text="Donation id in contract", verbose_name="contract donation id"
            ),
        ),
    ]
