# Generated by Django 5.0.4 on 2024-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("donations", "0004_alter_donation_on_chain_id"),
        ("pots", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donation",
            name="unique_pot_on_chain_id",
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pot__isnull", True)),
                fields=("on_chain_id",),
                name="unique_on_chain_id_when_pot_is_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pot__isnull", False)),
                fields=("on_chain_id", "pot"),
                name="unique_on_chain_id_with_pot",
            ),
        ),
    ]
