# Generated by Django 5.0.4 on 2024-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_remove_donation_unique_pot_on_chain_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="chef_fee",
            field=models.CharField(
                help_text="Chef fee.", max_length=64, null=True, verbose_name="chef fee"
            ),
        ),
    ]
