# Generated by Django 5.0.4 on 2024-05-07 18:57

from django.db import migrations

from ..models import Donation


class Migration(migrations.Migration):

    def set_chef_fee_none(apps, schema_editor):
        Donation.objects.update(chef_fee=None)

    dependencies = [
        ("donations", "0006_alter_donation_chef_fee"),
    ]

    operations = [
        migrations.RunPython(set_chef_fee_none),
    ]
