# Generated by Django 5.0.4 on 2024-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0007_auto_20240507_1857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="tx_hash",
            field=models.CharField(
                help_text="Transaction hash.",
                max_length=64,
                null=True,
                verbose_name="transaction hash",
            ),
        ),
    ]
