# Generated by Django 5.0.4 on 2024-06-20 13:04

from django.db import migrations


def migrate_ft_to_token(apps, schema_editor):
    Donation = apps.get_model("donations", "Donation")
    Token = apps.get_model("tokens", "Token")
    for donation in Donation.objects.all():
        token = Token.objects.get(id=donation.ft)
        donation.token = token
        donation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0009_donation_token"),
    ]

    operations = [
        migrations.RunPython(migrate_ft_to_token),
    ]
