# Generated by Django 5.0.4 on 2024-06-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0010_migrate_ft_to_token"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="ft",
        ),
        migrations.AlterField(
            model_name="donation",
            name="token",
            field=models.ForeignKey(
                help_text="Donation token.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="tokens.token",
            ),
        ),
    ]
