# Generated by Django 5.0.4 on 2024-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockHeight",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="saved block height.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="blockheight cache save",
                    ),
                ),
                (
                    "block_height",
                    models.IntegerField(
                        help_text="the last blockheight saved to db.",
                        verbose_name="blockheight value",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="block height last update at.",
                        verbose_name="updated at",
                    ),
                ),
            ],
        ),
    ]
