# Generated by Django 5.0.4 on 2024-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="referrer_fee",
            field=models.CharField(
                help_text="Referrer fee.",
                max_length=64,
                null=True,
                verbose_name="referrer fee",
            ),
        ),
    ]
