# Generated by Django 5.0.4 on 2024-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenHistoricalData",
            fields=[
                (
                    "token_id",
                    models.CharField(
                        db_index=True,
                        help_text="Token id.",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token id",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Last updated date.",
                        verbose_name="last updated",
                    ),
                ),
                (
                    "historical_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Historical price.",
                        max_digits=20,
                        verbose_name="historical price USD",
                    ),
                ),
            ],
        ),
    ]
