# Generated by Django 5.0.4 on 2024-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer_app", "0002_alter_donation_referrer_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="pot",
            name="admins",
            field=models.ManyToManyField(
                help_text="Pot admins.",
                related_name="admin_pot",
                to="indexer_app.account",
            ),
        ),
    ]
