# Generated by Django 5.0.4 on 2024-04-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer_app", "0003_pot_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pot",
            name="cooldown_period_ms",
            field=models.PositiveIntegerField(
                help_text="Pot cooldown period in ms.",
                null=True,
                verbose_name="cooldown period in ms",
            ),
        ),
    ]
