# Generated by Django 5.0.4 on 2024-04-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer_app", "0004_alter_pot_cooldown_period_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="listregistration",
            name="registered_by",
            field=models.ForeignKey(
                default="potlock.near",
                help_text="Account that did the registration.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_registrars",
                to="indexer_app.account",
            ),
            preserve_default=False,
        ),
    ]
