# Generated by Django 5.0.6 on 2024-07-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_near_social_profile_data"),
        ("nadabot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="rule id for group rules",
                        primary_key=True,
                        serialize=False,
                        verbose_name="rule id",
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        help_text="particular rule choice from the rule enum",
                        max_length=50,
                        verbose_name="rule enum choice",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="An optional value that rule choices might carry.",
                        null=True,
                        verbose_name="rule value",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="provider",
            name="stamp_count",
        ),
        migrations.AlterField(
            model_name="nadabotregistry",
            name="admins",
            field=models.ManyToManyField(
                help_text="registry admins.",
                related_name="nadabot_admin_registries",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="nadabotregistry",
            name="owner",
            field=models.ForeignKey(
                help_text="Nadabot Registry owner.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nadabot_owner_registries",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="submitted_by",
            field=models.ForeignKey(
                help_text="User who submitted this provider.",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
                verbose_name="submitted by",
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="Group id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="group id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="name given to the group",
                        max_length=100,
                        verbose_name="group name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Group creation date.", verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Group last update date.", verbose_name="updated at"
                    ),
                ),
                (
                    "providers",
                    models.ManyToManyField(
                        help_text="group providers.",
                        related_name="group_provider",
                        to="nadabot.provider",
                    ),
                ),
                (
                    "group_rule",
                    models.ForeignKey(
                        help_text="The rule this group uses.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadabot.rule",
                        verbose_name="rule",
                    ),
                ),
            ],
        ),
    ]
