# Generated by Django 5.0.6 on 2024-07-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nadabot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nadabotregistry",
            old_name="id",
            new_name="account",
        ),
    ]
