# Generated by Django 5.0.6 on 2024-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nadabot", "0002_rename_id_nadabotregistry_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="rule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Highest", "Highest"),
                    ("Lowest", "Lowest"),
                    ("Sum", "Sum"),
                    ("Diminishing_returns", "Diminishing Returns"),
                    ("Increasing_returns", "Increasing Returns"),
                ],
                help_text="The rule this group uses.",
                max_length=100,
                null=True,
                verbose_name="rule type",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="rule_val",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="An optional value that the group's rule choices might carry.",
                null=True,
                verbose_name="rule value",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="custom_args",
            field=models.CharField(
                blank=True,
                help_text="Custom args as Base64VecU8.",
                null=True,
                verbose_name="custom args",
            ),
        ),
    ]
