# Generated by Django 5.0.4 on 2024-05-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listupvote",
            options={"verbose_name_plural": "ListUpvotes"},
        ),
        migrations.AlterUniqueTogether(
            name="listupvote",
            unique_together={("list", "account")},
        ),
    ]
