# Generated by Django 5.0.4 on 2024-06-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_listupvote_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listupvote",
            options={"verbose_name_plural": "List Upvotes"},
        ),
    ]
