# Generated by Django 5.0.4 on 2024-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_listupvote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="on_chain_id",
            field=models.IntegerField(
                default=1,
                help_text="List ID in contract",
                unique=True,
                verbose_name="contract list ID",
            ),
            preserve_default=False,
        ),
    ]
