# Generated by Django 5.0.4 on 2024-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_list_on_chain_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="id",
            field=models.AutoField(
                help_text="List ID in DB (does not necessarily correspond to on-chain ID).",
                primary_key=True,
                serialize=False,
                verbose_name="list id",
            ),
        ),
    ]
