# Generated by Django 5.0.4 on 2024-06-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_near_social_profile_data"),
        ("lists", "0005_alter_list_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listregistration",
            unique_together={("list", "registrant")},
        ),
    ]
