# Generated by Django 5.0.6 on 2024-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_listregistration_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="Cover image url.",
                null=True,
                verbose_name="cover image url",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="List description.",
                max_length=256,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="listregistration",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Admin notes.",
                max_length=1024,
                null=True,
                verbose_name="admin notes",
            ),
        ),
        migrations.AlterField(
            model_name="listregistration",
            name="registrant_notes",
            field=models.TextField(
                blank=True,
                help_text="Registrant notes.",
                max_length=1024,
                null=True,
                verbose_name="registrant notes",
            ),
        ),
        migrations.AlterField(
            model_name="listregistration",
            name="tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash.",
                max_length=64,
                null=True,
                verbose_name="transaction hash",
            ),
        ),
    ]
