# Generated by Django 5.0.6 on 2025-09-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0003_add_stellar_chain"),
        ("lists", "0007_alter_list_cover_image_url_alter_list_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="chain",
            field=models.ForeignKey(
                default=1,
                help_text="Blockchain this list was created on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                related_query_name="list",
                to="chains.chain",
            ),
        ),
    ]
