# Generated by Django 5.0.6 on 2025-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("chains", "0003_add_stellar_chain"),
        ("lists", "0008_list_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="on_chain_id",
            field=models.IntegerField(
                help_text="List ID in contract", verbose_name="contract list ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="list",
            constraint=models.UniqueConstraint(
                fields=("on_chain_id", "chain"), name="unique_on_chain_id_per_chain"
            ),
        ),
    ]
