# Generated by Django 5.0.6 on 2025-10-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0009_alter_list_on_chain_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listregistration",
            name="on_chain_id",
            field=models.IntegerField(
                help_text="list registration id in contract",
                null=True,
                verbose_name="list registration id on chain",
            ),
        ),
    ]
