# Generated by Django 5.0.6 on 2025-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("lists", "0010_listregistration_on_chain_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listregistration",
            constraint=models.UniqueConstraint(
                fields=("on_chain_id", "list"), name="unique_on_chain_id_list"
            ),
        ),
    ]
