# Generated by Django 5.0.6 on 2025-07-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("tokens", "0006_rename_id_token_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on_chain_id", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "name",
                    models.TextField(help_text="Campaign name.", verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Campaign description.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "cover_image_url",
                    models.TextField(
                        blank=True,
                        help_text="Campaign cover image URL.",
                        null=True,
                        verbose_name="cover image URL",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Campaign start date.",
                        verbose_name="start at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Campaign end date.",
                        null=True,
                        verbose_name="end at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Campaign creation date.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "target_amount",
                    models.CharField(
                        help_text="Campaign target amount.",
                        max_length=64,
                        verbose_name="target amount",
                    ),
                ),
                (
                    "target_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="target amount in USD",
                    ),
                ),
                (
                    "min_amount",
                    models.CharField(
                        blank=True,
                        help_text="Campaign minimum amount.",
                        max_length=64,
                        null=True,
                        verbose_name="minimum amount",
                    ),
                ),
                (
                    "min_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="minimum amount in USD",
                    ),
                ),
                (
                    "max_amount",
                    models.CharField(
                        blank=True,
                        help_text="Campaign maximum amount.",
                        max_length=64,
                        null=True,
                        verbose_name="maximum amount",
                    ),
                ),
                (
                    "max_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="maximum amount in USD",
                    ),
                ),
                (
                    "total_raised_amount",
                    models.CharField(
                        default="0",
                        help_text="Campaign total raised amount.",
                        max_length=64,
                        verbose_name="total raised amount",
                    ),
                ),
                (
                    "total_raised_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total raised amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="total raised amount in USD",
                    ),
                ),
                (
                    "net_raised_amount",
                    models.CharField(
                        default="0",
                        help_text="Campaign net raised amount.",
                        max_length=64,
                        verbose_name="net raised amount",
                    ),
                ),
                (
                    "net_raised_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Net raised amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="net raised amount in USD",
                    ),
                ),
                (
                    "escrow_balance",
                    models.CharField(
                        default="0",
                        help_text="Campaign escrow balance.",
                        max_length=64,
                        verbose_name="escrow balance",
                    ),
                ),
                (
                    "escrow_balance_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Escrow balance in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="escrow balance in USD",
                    ),
                ),
                (
                    "referral_fee_basis_points",
                    models.PositiveIntegerField(
                        help_text="Referral fee basis points.",
                        verbose_name="referral fee basis points",
                    ),
                ),
                (
                    "creator_fee_basis_points",
                    models.PositiveIntegerField(
                        help_text="Creator fee basis points.",
                        verbose_name="creator fee basis points",
                    ),
                ),
                (
                    "allow_fee_avoidance",
                    models.BooleanField(
                        default=False,
                        help_text="Allow fee avoidance.",
                        verbose_name="allow fee avoidance",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Campaign owner.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_campaigns",
                        to="accounts.account",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Campaign recipient.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_of_campaign",
                        to="accounts.account",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign token (null for NEAR).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="tokens.token",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignDonation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Donation id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="donation id",
                    ),
                ),
                (
                    "on_chain_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Campaign donation id in contract",
                        verbose_name="campaign donation id",
                    ),
                ),
                (
                    "total_amount",
                    models.CharField(
                        help_text="Total amount.",
                        max_length=64,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "total_amount_usd",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        help_text="Total amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="total amount in USD",
                    ),
                ),
                (
                    "net_amount",
                    models.CharField(
                        help_text="Net amount.",
                        max_length=64,
                        verbose_name="net amount",
                    ),
                ),
                (
                    "net_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Net amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="net amount in USD",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Donation message.",
                        max_length=1024,
                        null=True,
                        verbose_name="message",
                    ),
                ),
                (
                    "donated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Donation date.",
                        verbose_name="donated at",
                    ),
                ),
                (
                    "protocol_fee",
                    models.CharField(
                        help_text="Protocol fee.",
                        max_length=64,
                        verbose_name="protocol fee",
                    ),
                ),
                (
                    "protocol_fee_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Protocol fee in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="protocol fee in USD",
                    ),
                ),
                (
                    "referrer_fee",
                    models.CharField(
                        blank=True,
                        help_text="Referrer fee.",
                        max_length=64,
                        null=True,
                        verbose_name="referrer fee",
                    ),
                ),
                (
                    "referrer_fee_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Referrer fee in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="referrer fee in USD",
                    ),
                ),
                (
                    "creator_fee",
                    models.CharField(
                        blank=True,
                        help_text="Creator fee.",
                        max_length=64,
                        null=True,
                        verbose_name="creator fee",
                    ),
                ),
                (
                    "creator_fee_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Creator fee in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="creator fee in USD",
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Donation returned date.",
                        null=True,
                        verbose_name="donation returned at",
                    ),
                ),
                (
                    "escrowed",
                    models.BooleanField(
                        default=False,
                        help_text="Is Donation Escrowed.",
                        verbose_name="escrowed donation",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash.",
                        max_length=64,
                        null=True,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Campaign donation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        help_text="Donor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_donations",
                        to="accounts.account",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Donation referrer.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_campaign_donations",
                        to="accounts.account",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        help_text="Donation token (null for NEAR).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_donations",
                        to="tokens.token",
                    ),
                ),
            ],
            options={
                "ordering": ["-donated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="campaigndonation",
            constraint=models.UniqueConstraint(
                fields=("on_chain_id", "campaign"), name="unique_campaign_donation_id"
            ),
        ),
    ]
