# Generated by Django 5.0.6 on 2024-11-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("chains", "0002_add_near_chain"),
        ("grantpicks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                help_text="Blockchain this round was created on.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                related_query_name="round",
                to="chains.chain",
            ),
        ),
        migrations.AddField(
            model_name="rounddeposit",
            name="memo",
            field=models.TextField(
                blank=True, help_text="Deposit memo.", null=True, verbose_name="memo"
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="approved_projects",
            field=models.ManyToManyField(
                help_text="Projects Approved for round.",
                related_name="rounds_approved_in",
                to="accounts.account",
            ),
        ),
    ]
