# Generated by Django 5.0.6 on 2024-11-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("grantpicks", "0002_round_chain_rounddeposit_memo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votepair",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_pairs",
                to="accounts.account",
            ),
        ),
    ]
