# Generated by Django 5.0.6 on 2024-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0003_add_stellar_chain"),
        ("grantpicks", "0003_alter_votepair_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="on_chain_id",
            field=models.IntegerField(
                help_text="Round ID in contract", verbose_name="contract round ID"
            ),
        ),
        migrations.AlterField(
            model_name="rounddeposit",
            name="on_chain_id",
            field=models.IntegerField(
                help_text="Deposit ID in contract", verbose_name="contract deposit ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("chain", "on_chain_id")},
        ),
        migrations.AlterUniqueTogether(
            name="rounddeposit",
            unique_together={("round", "on_chain_id")},
        ),
    ]
