# Generated by Django 5.0.6 on 2024-11-15 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("grantpicks", "0004_alter_round_on_chain_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votepair",
            name="project",
        ),
        migrations.AddField(
            model_name="votepair",
            name="projects",
            field=models.ManyToManyField(
                related_name="vote_pairs_included_in", to="accounts.account"
            ),
        ),
        migrations.AddField(
            model_name="votepair",
            name="voted_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_pairs_voted_for_in",
                to="accounts.account",
            ),
        ),
    ]
