# Generated by Django 5.0.6 on 2024-12-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grantpicks", "0005_remove_votepair_project_votepair_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="compliance_period_ms",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Compliance period in ms.",
                null=True,
                verbose_name="compliance period in ms",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="cooldown_period_ms",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Round cooldown period in ms.",
                null=True,
                verbose_name="cooldown period in ms",
            ),
        ),
    ]
