# Generated by Django 5.0.6 on 2025-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grantpicks", "0006_alter_round_compliance_period_ms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="use_whitelist",
        ),
        migrations.AddField(
            model_name="round",
            name="application_wl_list_id",
            field=models.IntegerField(
                help_text="list for applicants",
                null=True,
                verbose_name="list for applicants",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="use_whitelist_application",
            field=models.BooleanField(
                default=False,
                help_text="Use whitelist for application.",
                verbose_name="use whitelist",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="use_whitelist_voting",
            field=models.BooleanField(
                default=False,
                help_text="Use whitelist for voting.",
                verbose_name="use whitelist",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="voting_wl_list_id",
            field=models.IntegerField(
                help_text="list for voter whitelist",
                null=True,
                verbose_name="list for voter whitelist",
            ),
        ),
    ]
