# Generated by Django 5.0.6 on 2025-05-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grantpicks", "0007_remove_round_use_whitelist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="payout_address",
        ),
    ]
