# Generated by Django 5.0.6 on 2025-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grantpicks", "0008_remove_project_payout_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="minimum_deposit",
            field=models.CharField(
                default=10000000,
                help_text="Minimum deposit.",
                verbose_name="minimum deposit",
            ),
            preserve_default=False,
        ),
    ]
