# Generated by Django 5.0.6 on 2025-10-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grantpicks", "0009_round_minimum_deposit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
