# Generated by Django 5.0.4 on 2024-04-17 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        help_text="Token ID (address).",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                (
                    "decimals",
                    models.PositiveIntegerField(
                        help_text="Token decimals.", verbose_name="decimals"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TokenHistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Price timestamp.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in USD.",
                        max_digits=20,
                        verbose_name="price USD",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        help_text="Token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="tokens.token",
                    ),
                ),
            ],
        ),
    ]
