# Generated by Django 5.0.4 on 2024-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0004_alter_token_coingecko_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="coingecko_id",
            field=models.CharField(
                blank=True,
                help_text="Token id on coingecko.",
                max_length=255,
                null=True,
                verbose_name="coingecko_id",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="icon",
            field=models.TextField(
                blank=True,
                help_text="Token icon (base64 data URL).",
                null=True,
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Token name.",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text="Token symbol.",
                max_length=255,
                null=True,
                verbose_name="symbol",
            ),
        ),
    ]
