# Generated by Django 5.0.6 on 2024-07-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0005_alter_token_coingecko_id_alter_token_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="id",
            new_name="account",
        ),
    ]
