# Generated by Django 5.0.4 on 2024-04-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pot",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        help_text="Pot account ID.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pot",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Pot deployment date.",
                        verbose_name="deployed at",
                    ),
                ),
                (
                    "source_metadata",
                    models.JSONField(
                        help_text="Pot source metadata.", verbose_name="source metadata"
                    ),
                ),
                ("name", models.TextField(help_text="Pot name.", verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        help_text="Pot description.", verbose_name="description"
                    ),
                ),
                (
                    "max_approved_applicants",
                    models.PositiveIntegerField(
                        help_text="Max approved applicants.",
                        verbose_name="max approved applicants",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        help_text="Base currency.",
                        max_length=64,
                        null=True,
                        verbose_name="base currency",
                    ),
                ),
                (
                    "application_start",
                    models.DateTimeField(
                        help_text="Pot application start date.",
                        verbose_name="application start",
                    ),
                ),
                (
                    "application_end",
                    models.DateTimeField(
                        help_text="Pot application end date.",
                        verbose_name="application end",
                    ),
                ),
                (
                    "matching_round_start",
                    models.DateTimeField(
                        help_text="Pot matching round start date.",
                        verbose_name="matching round start",
                    ),
                ),
                (
                    "matching_round_end",
                    models.DateTimeField(
                        help_text="Pot matching round end date.",
                        verbose_name="matching round end",
                    ),
                ),
                (
                    "registry_provider",
                    models.CharField(
                        help_text="Registry provider.",
                        max_length=64,
                        null=True,
                        verbose_name="registry provider",
                    ),
                ),
                (
                    "min_matching_pool_donation_amount",
                    models.CharField(
                        help_text="Min matching pool donation amount.",
                        max_length=64,
                        verbose_name="min matching pool donation amount",
                    ),
                ),
                (
                    "sybil_wrapper_provider",
                    models.CharField(
                        help_text="Sybil wrapper provider.",
                        max_length=64,
                        null=True,
                        verbose_name="sybil wrapper provider",
                    ),
                ),
                (
                    "custom_sybil_checks",
                    models.CharField(
                        help_text="Custom sybil checks.",
                        max_length=64,
                        null=True,
                        verbose_name="custom sybil checks",
                    ),
                ),
                (
                    "custom_min_threshold_score",
                    models.PositiveIntegerField(
                        help_text="Custom min threshold score.",
                        null=True,
                        verbose_name="custom min threshold score",
                    ),
                ),
                (
                    "referral_fee_matching_pool_basis_points",
                    models.PositiveIntegerField(
                        help_text="Referral fee matching pool basis points.",
                        verbose_name="referral fee matching pool basis points",
                    ),
                ),
                (
                    "referral_fee_public_round_basis_points",
                    models.PositiveIntegerField(
                        help_text="Referral fee public round basis points.",
                        verbose_name="referral fee public round basis points",
                    ),
                ),
                (
                    "chef_fee_basis_points",
                    models.PositiveIntegerField(
                        help_text="Chef fee basis points.",
                        verbose_name="chef fee basis points",
                    ),
                ),
                (
                    "total_matching_pool",
                    models.CharField(
                        help_text="Total matching pool.",
                        max_length=64,
                        verbose_name="total matching pool",
                    ),
                ),
                (
                    "total_matching_pool_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total matching pool in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="total matching pool in USD",
                    ),
                ),
                (
                    "matching_pool_balance",
                    models.CharField(
                        help_text="Matching pool balance.",
                        max_length=64,
                        verbose_name="matching pool balance",
                    ),
                ),
                (
                    "matching_pool_donations_count",
                    models.PositiveIntegerField(
                        help_text="Matching pool donations count.",
                        verbose_name="matching pool donations count",
                    ),
                ),
                (
                    "total_public_donations",
                    models.CharField(
                        help_text="Total public donations.",
                        max_length=64,
                        verbose_name="total public donations",
                    ),
                ),
                (
                    "total_public_donations_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total public donations in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="total public donations in USD",
                    ),
                ),
                (
                    "public_donations_count",
                    models.PositiveIntegerField(
                        help_text="Public donations count.",
                        verbose_name="public donations count",
                    ),
                ),
                (
                    "cooldown_end",
                    models.DateTimeField(
                        help_text="Pot cooldown end date.",
                        null=True,
                        verbose_name="cooldown end",
                    ),
                ),
                (
                    "cooldown_period_ms",
                    models.PositiveIntegerField(
                        help_text="Pot cooldown period in ms.",
                        null=True,
                        verbose_name="cooldown period in ms",
                    ),
                ),
                (
                    "all_paid_out",
                    models.BooleanField(
                        help_text="All paid out.", verbose_name="all paid out"
                    ),
                ),
                (
                    "protocol_config_provider",
                    models.CharField(
                        help_text="Protocol config provider.",
                        max_length=64,
                        null=True,
                        verbose_name="protocol config provider",
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        help_text="Pot admins.",
                        related_name="admin_pots",
                        to="accounts.account",
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        help_text="Pot chef.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chef_pots",
                        to="accounts.account",
                    ),
                ),
                (
                    "deployer",
                    models.ForeignKey(
                        help_text="Pot deployer.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployed_pots",
                        to="accounts.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Pot owner.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_pots",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PotApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Application id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="application id",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Application message.",
                        max_length=1024,
                        null=True,
                        verbose_name="message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("InReview", "InReview"),
                        ],
                        help_text="Application status.",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Application submission date.",
                        verbose_name="submitted at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Application last update date.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="Transaction hash.",
                        max_length=64,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Account that applied to the pot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pot_applications",
                        to="accounts.account",
                    ),
                ),
                (
                    "pot",
                    models.ForeignKey(
                        help_text="Pot applied to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PotApplicationReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Review id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="review id",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        help_text="Review notes.",
                        max_length=1024,
                        null=True,
                        verbose_name="notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("InReview", "InReview"),
                        ],
                        help_text="Application status for this review.",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        help_text="Review date.", verbose_name="reviewed at"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="Transaction hash.",
                        max_length=64,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="pots.potapplication",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Account that reviewed the application.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pot_application_reviews",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PotFactory",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        help_text="Pot factory account ID.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pot_factory",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(
                        help_text="Pot factory deployment date.",
                        verbose_name="deployed at",
                    ),
                ),
                (
                    "source_metadata",
                    models.JSONField(
                        help_text="Pot factory source metadata.",
                        null=True,
                        verbose_name="source metadata",
                    ),
                ),
                (
                    "protocol_fee_basis_points",
                    models.PositiveIntegerField(
                        help_text="Pot factory protocol fee basis points.",
                        verbose_name="protocol fee basis points",
                    ),
                ),
                (
                    "require_whitelist",
                    models.BooleanField(
                        help_text="Require whitelist.", verbose_name="require whitelist"
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        help_text="Pot factory admins.",
                        related_name="admin_pot_factories",
                        to="accounts.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Pot factory owner.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_pot_factories",
                        to="accounts.account",
                    ),
                ),
                (
                    "protocol_fee_recipient",
                    models.ForeignKey(
                        help_text="Pot factory protocol fee recipient.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pot_factories_protocol_fee_recipient",
                        to="accounts.account",
                    ),
                ),
                (
                    "whitelisted_deployers",
                    models.ManyToManyField(
                        help_text="Pot factory whitelisted deployers.",
                        related_name="whitelisted_pot_factories",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pot",
            name="pot_factory",
            field=models.ForeignKey(
                help_text="Pot factory.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pots",
                to="pots.potfactory",
            ),
        ),
        migrations.CreateModel(
            name="PotPayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Payout id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="payout id",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        help_text="Payout amount.", max_length=64, verbose_name="amount"
                    ),
                ),
                (
                    "amount_paid_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payout amount in USD.",
                        max_digits=20,
                        null=True,
                        verbose_name="amount paid in USD",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        db_index=True, help_text="Payout date.", verbose_name="paid at"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="Transaction hash.",
                        max_length=64,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "ft",
                    models.ForeignKey(
                        help_text="Payout FT.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ft_pot_payouts",
                        to="accounts.account",
                    ),
                ),
                (
                    "pot",
                    models.ForeignKey(
                        help_text="Pot that this payout is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="pots.pot",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Payout recipient.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pot_payouts",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PotPayoutChallenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Challenge id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="challenge id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Challenge creation date.", verbose_name="created at"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Challenge message.",
                        max_length=1024,
                        verbose_name="message",
                    ),
                ),
                (
                    "challenger",
                    models.ForeignKey(
                        help_text="Payout challenger.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pot_payout_challenges",
                        to="accounts.account",
                    ),
                ),
                (
                    "pot",
                    models.ForeignKey(
                        help_text="Pot challenged.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PotPayoutChallengeAdminResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Admin response id.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Admin response id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Admin response creation date.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Admin response message.",
                        max_length=1024,
                        verbose_name="message",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        help_text="Admin response resolution status.",
                        verbose_name="resolved",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="Transaction hash.",
                        max_length=64,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        help_text="Admin that responded to the challenge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pot_payout_challenge_admin_responses",
                        to="accounts.account",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        help_text="Challenge responded to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_responses",
                        to="pots.potpayoutchallenge",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pot",
            index=models.Index(
                fields=["application_start", "application_end"],
                name="idx_application_period",
            ),
        ),
        migrations.AddIndex(
            model_name="pot",
            index=models.Index(
                fields=["matching_round_start", "matching_round_end"],
                name="idx_matching_period",
            ),
        ),
    ]
