# Generated by Django 5.0.4 on 2024-05-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("pots", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="potapplication",
            options={"verbose_name_plural": "PotApplications"},
        ),
        migrations.AlterModelOptions(
            name="potapplicationreview",
            options={"verbose_name_plural": "PotApplicationReviews"},
        ),
        migrations.AlterModelOptions(
            name="potpayoutchallenge",
            options={"verbose_name_plural": "PayoutChallenges"},
        ),
        migrations.AlterModelOptions(
            name="potpayoutchallengeadminresponse",
            options={"verbose_name_plural": "PotPayoutChallengeResponses"},
        ),
        migrations.AddField(
            model_name="potpayoutchallengeadminresponse",
            name="challenger",
            field=models.ForeignKey(
                help_text="challenger being responded to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout_admin_responses",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="potpayoutchallengeadminresponse",
            name="pot",
            field=models.ForeignKey(
                help_text="Pot being challenged.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout_responses",
                to="pots.pot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="potpayoutchallengeadminresponse",
            unique_together={("challenger", "pot", "created_at")},
        ),
        migrations.AlterUniqueTogether(
            name="potapplication",
            unique_together={("pot", "applicant")},
        ),
        migrations.AlterUniqueTogether(
            name="potapplicationreview",
            unique_together={("application", "reviewer", "reviewed_at")},
        ),
        migrations.AlterUniqueTogether(
            name="potpayoutchallenge",
            unique_together={("challenger", "pot")},
        ),
        migrations.RemoveField(
            model_name="potpayoutchallengeadminresponse",
            name="challenge",
        ),
    ]
