# Generated by Django 5.0.4 on 2024-06-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0002_alter_potapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="potapplication",
            options={"verbose_name_plural": "Pot Applications"},
        ),
        migrations.AlterModelOptions(
            name="potapplicationreview",
            options={"verbose_name_plural": "Pot Application Reviews"},
        ),
        migrations.AlterModelOptions(
            name="potfactory",
            options={"verbose_name_plural": "Pot Factories"},
        ),
        migrations.AlterModelOptions(
            name="potpayoutchallenge",
            options={"verbose_name_plural": "Payout Challenges"},
        ),
        migrations.AlterModelOptions(
            name="potpayoutchallengeadminresponse",
            options={"verbose_name_plural": "Payout Challenge Responses"},
        ),
    ]
