# Generated by Django 5.0.4 on 2024-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0004_alter_potapplication_tx_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potapplication",
            name="updated_at",
            field=models.DateTimeField(
                help_text="Application last update date.",
                null=True,
                verbose_name="updated at",
            ),
        ),
    ]
