# Generated by Django 5.0.4 on 2024-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0005_alter_potapplication_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pot",
            name="custom_sybil_checks",
            field=models.CharField(
                help_text="Custom sybil checks.",
                null=True,
                verbose_name="custom sybil checks",
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="matching_pool_balance",
            field=models.CharField(
                help_text="Matching pool balance.", verbose_name="matching pool balance"
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="min_matching_pool_donation_amount",
            field=models.CharField(
                help_text="Min matching pool donation amount.",
                verbose_name="min matching pool donation amount",
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="protocol_config_provider",
            field=models.CharField(
                help_text="Protocol config provider.",
                null=True,
                verbose_name="protocol config provider",
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="registry_provider",
            field=models.CharField(
                help_text="Registry provider.",
                null=True,
                verbose_name="registry provider",
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="sybil_wrapper_provider",
            field=models.CharField(
                help_text="Sybil wrapper provider.",
                null=True,
                verbose_name="sybil wrapper provider",
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="total_matching_pool",
            field=models.CharField(
                help_text="Total matching pool.", verbose_name="total matching pool"
            ),
        ),
        migrations.AlterField(
            model_name="pot",
            name="total_public_donations",
            field=models.CharField(
                help_text="Total public donations.",
                verbose_name="total public donations",
            ),
        ),
        migrations.AlterField(
            model_name="potapplication",
            name="tx_hash",
            field=models.CharField(
                help_text="Transaction hash.",
                null=True,
                verbose_name="transaction hash",
            ),
        ),
        migrations.AlterField(
            model_name="potapplicationreview",
            name="tx_hash",
            field=models.CharField(
                help_text="Transaction hash.",
                null=True,
                verbose_name="transaction hash",
            ),
        ),
        migrations.AlterField(
            model_name="potpayout",
            name="amount",
            field=models.CharField(help_text="Payout amount.", verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="potpayout",
            name="tx_hash",
            field=models.CharField(
                help_text="Transaction hash.",
                null=True,
                verbose_name="transaction hash",
            ),
        ),
        migrations.AlterField(
            model_name="potpayoutchallengeadminresponse",
            name="tx_hash",
            field=models.CharField(
                help_text="Transaction hash.",
                null=True,
                verbose_name="transaction hash",
            ),
        ),
    ]
