# Generated by Django 5.0.4 on 2024-06-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0006_alter_pot_custom_sybil_checks_and_more"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="potpayout",
            name="token",
            field=models.ForeignKey(
                help_text="Payout token.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pot_payouts",
                to="tokens.token",
            ),
        ),
    ]
