# Generated by Django 5.0.4 on 2024-06-20 13:04

from django.db import migrations


def migrate_ft_to_token(apps, schema_editor):
    PotPayout = apps.get_model("pots", "PotPayout")
    Token = apps.get_model("tokens", "Token")
    for payout in PotPayout.objects.all():
        token = Token.objects.get(id=payout.ft)
        payout.token = token
        payout.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0007_potpayout_token"),
    ]

    operations = [
        migrations.RunPython(migrate_ft_to_token),
    ]
