# Generated by Django 5.0.4 on 2024-06-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pots", "0008_migrate_ft_to_token"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="potpayout",
            name="ft",
        ),
        migrations.AlterField(
            model_name="potpayout",
            name="token",
            field=models.ForeignKey(
                help_text="Payout token.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pot_payouts",
                to="tokens.token",
            ),
        ),
    ]
