# Generated by Django 5.0.6 on 2024-11-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_near_social_profile_data"),
        ("pots", "0015_alter_potpayout_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potapplication",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project that applied.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="accounts.account",
            ),
        ),
    ]
